version: '3.8'

services:
  tg-sota-feedback:
    image: tg-sota-feedback
    container_name: backend-test
    build: ./
    command: ./wait-for-postgres.sh db ./backend-testdock
    ports:
      - 8090:8090
    depends_on:
      - db
    env_file:
      - .env


  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
