version: '3.8'

services:

  redis:
    image: 'bitnami/redis:latest'
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    env_file:
      - .env

  tg-sota-feedback:
    image: tg-sota-feedback
    build: ./
    depends_on:
      - redis
    env_file:
      - .env
