version: '3.3'

services:
  redis:
    image: 'redis:latest'
    env_file:
      - .env
    restart: unless-stopped

  tg-sota-feedback:
    image: tg-sota-feedback
    build: ./
    depends_on:
      - redis
    env_file:
      - .env
